# Generated by Django 2.2.6 on 2019-10-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_one', models.IntegerField()),
                ('data_two', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculated_value', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'permissions': [('index_manager', 'Index Manager')],
            },
        ),
    ]
