# Generated by Django 2.2.6 on 2019-10-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('index_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_one', models.IntegerField(verbose_name='data one')),
                ('data_two', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='data two')),
                ('calculated_value', models.CharField(blank=True, max_length=32, verbose_name='calculated value')),
            ],
            options={
                'ordering': ['id'],
                'permissions': [('index_manager', 'Index Manager')],
            },
        ),
    ]
