# Generated by Django 2.2.6 on 2019-10-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(choices=[('101', '101'), ('102', '102')], max_length=3)),
                ('department', models.CharField(choices=[('dept_one', 'Direccion ONE'), ('dept_two', 'Direccion TWO')], max_length=30)),
                ('index_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
