# Generated by Django 2.2.6 on 2019-10-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('107', '107'), ('108', '108'), ('109', '109'), ('110', '110')], max_length=3)),
                ('department', models.CharField(choices=[('AR', 'Análisis de Riesgos'), ('AH', 'Asistencia Humanitaria'), ('CGAJ', 'Cordinación General de Asesoría Jurídica'), ('EIRD', 'Estratégia Internacionales para la Reducción de Riesgos'), ('FDCGR', 'Fortalecimiento y Desarrollo de capacidades en Gestión de Riesgos'), ('GI', 'Gestión de la Información'), ('GR', 'Gestión de Riesgos'), ('MEA', 'Monitoreo de Eventos Adversos'), ('OP', 'Operaciones'), ('PEGR', 'Política y Estandares de Gestión de Riesgos')], max_length=5)),
                ('index_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
