# Generated by Django 2.2.6 on 2019-10-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('107', '107'), ('108', '108'), ('109', '109'), ('110', '110')], max_length=3, verbose_name='sequence')),
                ('department', models.CharField(choices=[('Análisis de Riesgos', 'Análisis de Riesgos'), ('Asistencia Humanitaria', 'Asistencia Humanitaria'), ('Cordinación General de Asesoría Jurídica', 'Cordinación General de Asesoría Jurídica'), ('Estratégia Internacionales para la Reducción de Riesgos', 'Estratégia Internacionales para la Reducción de Riesgos'), ('Fortalecimiento y Desarrollo de capacidades en Gestión de Riesgos', 'Fortalecimiento y Desarrollo de capacidades en Gestión de Riesgos'), ('Gestión de la Información', 'Gestión de la Información'), ('Gestión de Riesgos', 'Gestión de Riesgos'), ('Monitoreo de Eventos Adversos', 'Monitoreo de Eventos Adversos'), ('Operaciones', 'Operaciones'), ('Política y Estandares de Gestión de Riesgos', 'Política y Estandares de Gestión de Riesgos')], max_length=100, verbose_name='department')),
                ('index_name', models.CharField(max_length=50, verbose_name='index name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
